// st quis, imperdiet viverra tellus. Donec vitae vehicula magna. Proin 
export const endP = ({
    courseId,
    userId,
    pubId,
    commentId,
    email,
    groupId,
    courseCode,
    submission_id,
    nota,
    publication_id,
}) => {
    // console.log('endP commentId ', {
    //     courseId,
    //     userId,
    //     pubId,
    //     commentId,
    //     email,
    // })
    return {
        calificateSubmission:`/submission/calificate/${userId}/${publication_id}/${nota}`,
        createCourse: '/course',
        createGroup: `/group/create/${courseId}/default`,
        createSubmission:'/submission',
        createUser: '/user',
        delegateUser: `/course/${courseId}/delegate/${userId}`,
        editCourse: `/course/edit/${courseId}`,
        editUser: `user/${email}`,
        enrollCourseByMail: `/course/${courseId}/enroll/by_email/${email}`,
        enrollMeByCode: `/course/${courseCode}/enroll_me`,
        getInscriptions: `/course/${courseId}/inscriptions`,
        getCourse: `/course/${courseId}`,
        getCourses: '/course',
        getGroups: `/group/${courseId}`,
        getSubmissions:`/submission/${publication_id}`,
        getUser: `/user/${userId}`,
        getUserByEmail: `/user/byemail/${email}`,
        getUsers: '/user',
        getComments: `/comment/publication/${pubId}`,
        getAnswers: `/comment/sub/${commentId}`,
        lockAllGroups: `/group/lock_all/${courseId}`,
        lockGroup: `/group/lock/${groupId}`,
        postAnnounce: `/publication/exam/${courseId}`,
        postAnswer: `/comment/${commentId}`,
        postComment: `/publication/${pubId}/comment`,
        postExam: `/publication/exam/${courseId}`,
        postMaterial: `/publication/material/${courseId}`,
        postTask: `/publication/assignment/${courseId}`,
    }
}
